;-----------------------------------------------------------------------------
;-----------------------------------------------------------------------------
;template-SUB.inc
;-----------------------------------------------------------------------------
;-----------------------------------------------------------------------------
; Include this file at the end of the program, before the "END" statement:
;#INCLUDE subroutine.inc

; For short operations, use macros
; Subroutines have the overhead of saving/retrieving the program counter and registers 
; when jumping and returning from the subroutine code.

;-----------------------------------------------------------------------------
;-----------------------------------------------------------------------------
